
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.ssl.protocols=TLSv1.2

mail.sender.email=saniulsami@gmail.com
mail.sender.password=thfh meuapuee mwwc
mail.sender.name=RUET Hall Management System
